---
- hosts: windows
  vars:
    java:
      JAVA_HOME: "C:\\Program Files\\Java\\jdk1.7.0._76"
  tasks:
    - name: install and set java
      win_chocolatey:
        name: jdk7 -y
        version: 7.0.76
        environment: java
        state: present
    - name: set environment
      win_environment:
        state: present
        name: JAVA_HOME
        value: "C:\\Program Files\\Java\\jdk1.7.0._76"
        level: machine
    - name: Install Apache Tomcat
      win_chocolatey:
        name: tomcat
        version: 8.0.33
    - name: Install Eclipse Luna Java EE IDE
      win_get_url: 
        url: http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/luna/SR2/eclipse-jee-luna-SR2-win32-x86_64.zip&r=1
        dest: "C:\\Users\\Amina\\eclipse-jee-luna-SR2-win32-x86_64.zip"
    - name: Grab PSCX msi
      win_get_url:
        url: "http://download-codeplex.sec.s-msft.com/Download/Release?ProjectName=pscx&DownloadId=923562&FileTime=130585918034470000&Build=20959"
        dest: "C:\\pscx.msi"
    - name: Install PSCX msi
      win_msi:
        path: "C:\\pscx.msi"
    - name: unzip eclipse
      win_unzip:  
        src: "C:\\Users\\Amina\\eclipse-jee-luna-SR2-win32-x86_64.zip"
        dest: "C:\\Users\\Amina\\tools"
